## Principal Component Analysis (PCA) Explained

PCA is a dimensionality reduction technique that transforms high-dimensional data into a lower-dimensional space while preserving as much variance as possible. Here's how it works:

#### The Core Idea

Imagine a dataset with many features. PCA finds new axes (called **principal components**) that capture the directions of maximum variance in your data. The first component points in the direction where data varies the most, the second captures the next-largest variance (perpendicular to the first), and so on.

#### Step-by-Step Process

**1. Standardization**
- Center the data (subtract the mean from each feature)
- Scale features to have unit variance (divide by standard deviation)
- This ensures features with large ranges don't dominate

**2. Compute the Covariance Matrix**
- Calculate how each feature co-varies with every other feature
- This is an n×n matrix (n = number of features)

**3. Eigenvalue Decomposition**
- Find the eigenvectors and eigenvalues of the covariance matrix
- **Eigenvectors**: directions of the principal components
- **Eigenvalues**: variance explained along each direction
- Larger eigenvalues = more important components

**4. Sort and Select Components**
- Sort eigenvectors by eigenvalue (largest first)
- Choose the top k components you want to keep
- These are your new axes

**5. Project Data**
- Transform your original data onto the new principal component axes
- Result: lower-dimensional representation that retains the most important information

#### Visual Intuition

Think of a 3D cloud of points:
- If all points roughly align along a line, most variance is on that line → PCA captures it in PC1
- If there's spread perpendicular to that line, PC2 captures that secondary direction
- PC3 would capture noise or minor variations

By keeping just PC1 and PC2, you've reduced from 3D to 2D while losing minimal information.

#### Key Concepts

**Variance Explained**: Each component's eigenvalue tells you what fraction of total variance it explains. You can plot cumulative variance vs. number of components to decide how many to keep (often aim for 95%+ cumulative variance).

**Orthogonality**: Components are perpendicular to each other—no redundancy.

**Linear Only**: PCA assumes linear relationships. Nonlinear variants (kernel PCA, autoencoders) handle curved structures.

#### Common Use Cases

- **Feature reduction** before training ML models (especially when you have 100s of features)
- **Visualization** (project to 2D/3D for plotting)
- **Noise reduction** (discard low-variance components that may be noise)
- **Data exploration** (understand which feature combinations matter most)

#### Pros & Cons

**Pros:**
- Simple, interpretable, fast
- Unsupervised (doesn't require labels)
- Mathematically elegant

**Cons:**
- Only captures linear variance
- New components are hard to interpret (mixture of original features)
- Sensitive to scaling
- May not help if variance isn't the right notion of "importance" for your task
#
---

In [46]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plot
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

from sklearn import datasets

In [47]:
X,y = datasets.load_iris(return_X_y=True)

#### 1) Standardalization

In [48]:
X_stand = StandardScaler().fit_transform(X)

#### 2) Correlation Matrix

In [49]:
X_corr = pd.DataFrame(X_stand).cov()

#### 3) Eigenvalue and Eigenvectors

In [50]:
eigenvalues, eigenvectors = np.linalg.eig(X_corr)

In [51]:
eigenvalues

array([2.93808505, 0.9201649 , 0.14774182, 0.02085386])

In [52]:
idx = eigenvalues.argsort()[::-1]
idx

array([0, 1, 2, 3])

In [53]:
eigenvalues = eigenvalues[idx]
eigenvalues

array([2.93808505, 0.9201649 , 0.14774182, 0.02085386])

In [54]:
eigenvector = eigenvectors[:, idx]
eigenvector

array([[ 0.52106591, -0.37741762, -0.71956635,  0.26128628],
       [-0.26934744, -0.92329566,  0.24438178, -0.12350962],
       [ 0.5804131 , -0.02449161,  0.14212637, -0.80144925],
       [ 0.56485654, -0.06694199,  0.63427274,  0.52359713]])

#### 4) PC1, PC2

In [55]:
pc1 = eigenvector[:,0]
pc1

array([ 0.52106591, -0.26934744,  0.5804131 ,  0.56485654])

In [56]:
pc2 = eigenvector[:, 1]
pc2

array([-0.37741762, -0.92329566, -0.02449161, -0.06694199])

#### 5) Apply each sample to pc1 and pc2

In [ ]:
X_stand[0,:] @ pc1

np.float64(-2.2647028088075896)

In [59]:
X_stand[0,:] @ pc2

np.float64(-0.4800265965209867)

#### 6) Comparison with sklearn.decomposition (PCA)

In [61]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# Load and standardize data
iris = load_iris()
X = iris.data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


In [63]:
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

In [65]:
X_pca[:2]

array([[-2.26470281,  0.4800266 ],
       [-2.08096115, -0.67413356]])

#### 7) All information together

In [42]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler

# Load and standardize data
iris = load_iris()
X = iris.data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Compute covariance matrix
cov_matrix = np.cov(X_scaled.T)

# Get eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

# Sort by eigenvalue (descending)
idx = eigenvalues.argsort()[::-1]
eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:, idx]

# First principal component (largest eigenvalue)
pc1 = eigenvectors[:, 0]
print(pc1)
# Output: [ 0.36 -0.08  0.86  0.36]
print(f"Eigenvalue: {eigenvalues[0]:.2f}")  # 2.91

[ 0.52106591 -0.26934744  0.5804131   0.56485654]
Eigenvalue: 2.94
