In [3]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [4]:
tf.__version__

'2.20.0'

In [5]:
np.set_printoptions(precision=3)

In [6]:
a = np.array([1,2,3], dtype=np.int32)

In [7]:
b = [4,5,6]

In [8]:
a

array([1, 2, 3], dtype=int32)

In [9]:
b

[4, 5, 6]

In [10]:
t_a = tf.convert_to_tensor(a)

In [11]:
t_a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [12]:
t_b = tf.convert_to_tensor(b)

In [13]:
t_b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6], dtype=int32)>

In [14]:
print(t_a)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [15]:
print(t_b)

tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [16]:
t_ones = tf.ones((2,3))

In [17]:
t_ones

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [18]:
print(t_ones)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [19]:
t_ones.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [21]:
const_tensor = tf.constant([1.2, 5, np.pi],
                           dtype = tf.float32)

In [22]:
const_tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.2  , 5.   , 3.142], dtype=float32)>

In [23]:
print(const_tensor)

tf.Tensor([1.2   5.    3.142], shape=(3,), dtype=float32)


In [24]:
tf.random.set_seed(1)
t1 = tf.random.uniform(shape=(5,2),
                       minval=-1.0,
                       maxval=1.0)
t2 = tf.random.normal(shape=(5,2),
                      mean=0.0,
                      stddev=1.0)

In [25]:
t1 * t2

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[-0.27 , -0.874],
       [-0.017, -0.175],
       [-0.296, -0.139],
       [-0.727,  0.135],
       [-0.401,  0.004]], dtype=float32)>

In [26]:
t1

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[-0.67 ,  0.803],
       [ 0.262, -0.131],
       [-0.416,  0.285],
       [ 0.952, -0.13 ],
       [ 0.32 ,  0.21 ]], dtype=float32)>

In [29]:
tf.math.reduce_mean(t1, axis=0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.09 , 0.207], dtype=float32)>

In [30]:
tf.linalg.matmul(t1, t2, transpose_b=True)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-1.144,  1.115, -0.87 , -0.321,  0.856],
       [ 0.248, -0.191,  0.25 , -0.064, -0.331],
       [-0.478,  0.407, -0.436,  0.022,  0.527],
       [ 0.525, -0.234,  0.741, -0.593, -1.194],
       [-0.099,  0.26 ,  0.125, -0.462, -0.396]], dtype=float32)>

In [31]:
tf.random.set_seed(1)
t_x = tf.random.uniform([4, 3], dtype=tf.float32)
t_y = tf.range(4)

In [32]:
t_x

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.165, 0.901, 0.631],
       [0.435, 0.292, 0.643],
       [0.976, 0.435, 0.66 ],
       [0.605, 0.637, 0.614]], dtype=float32)>

In [33]:
t_y

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>

In [34]:
ds_x = tf.data.Dataset.from_tensor_slices(t_x)
ds_y = tf.data.Dataset.from_tensor_slices(t_y)

In [36]:
ds_joint = tf.data.Dataset.zip((ds_x, ds_y))

In [37]:
ds_joint

<_ZipDataset element_spec=(TensorSpec(shape=(3,), dtype=tf.float32, name=None), TensorSpec(shape=(), dtype=tf.int32, name=None))>

In [45]:
for example in ds_joint:
    print(example[0].numpy())
    print(example[1].numpy())

[0.165 0.901 0.631]
0
[0.435 0.292 0.643]
1
[0.976 0.435 0.66 ]
2
[0.605 0.637 0.614]
3


In [46]:
ds_joint.batch(3)

<_BatchDataset element_spec=(TensorSpec(shape=(None, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>

In [49]:
import tensorflow_datasets as tfds

In [50]:
len(tfds.list_builders())

2026-05-07 20:22:05.569086: W external/local_xla/xla/tsl/platform/cloud/google_auth_provider.cc:185] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "NOT_FOUND: Could not locate the credentials file.". Retrieving token from GCE failed with "FAILED_PRECONDITION: Error executing an HTTP request: libcurl code 6 meaning 'Could not resolve hostname', error details: Could not resolve host: metadata.google.internal".


1315